### PR TITLE
Added makeTransaction (untested)

### PR DESCRIPTION
**Pull request by Lemmmy**
asdfghjkl

### CODE REVIEW

**Comment by Lignum** [comment]
:ok: :+1:

**Comment by Lemmmy** [comment]
:cool:

**Comment by Luca0208** [comment]
This is my code except the error and I just tested mine. Works!

**Comment by Lemmmy** [comment]
i amde myine from scratch

**Comment by Luca0208** [comment]
well there aren't that many ways of implementing transactions, seems like we chose the same

**Pull request merged**
